// Generates examples/validation-app/config.js (gitignored) from
// examples/validation-app/.env — run this after filling in .env:
//
//   node examples/validation-app/generate-config.mjs
//
// Real exported environment variables (e.g. set by CI or your shell) also
// work: dotenv only fills in vars that aren't already set in process.env.
import dotenv from 'dotenv';
import fs from 'fs';

dotenv.config({ path: new URL('./.env', import.meta.url).pathname });

/**
 * Builds one environment's config block, or null if it isn't configured.
 * @param {string} suffix - 'DEV' or 'PROD'
 * @param {string} networkHost
 */
function buildEnvBlock(suffix, networkHost) {
  const apiKey = process.env[`C3D_APPLICATION_API_KEY_${suffix}`];
  const sceneName = process.env[`C3D_SCENE_NAME_${suffix}`];
  const sceneId = process.env[`C3D_SCENE_ID_${suffix}`];
  const versionNumber = process.env[`C3D_SCENE_VERSION_${suffix}`] || '1';

  if (!apiKey || !sceneId) {
    return null;
  }

  if (!sceneName) {
    console.warn(
      `[generate-config] C3D_SCENE_NAME_${suffix} is empty — c3d.setScene() needs the ` +
        'exact scene name to match allSceneData, so this env will likely fail to select a scene.'
    );
  }

  return {
    apiKey,
    networkHost,
    scene: {
      sceneName: sceneName || '',
      sceneId,
      versionNumber
    }
  };
}

const dev = buildEnvBlock('DEV', 'data.c3ddev.com');
const prod = buildEnvBlock('PROD', 'data.cognitive3d.com');

const banner =
  '// GENERATED by generate-config.mjs — do not edit, do not commit.\n' +
  '// Regenerate any time by re-running: node examples/validation-app/generate-config.mjs\n';

const body = `window.C3D_VALIDATION_CONFIG = ${JSON.stringify({ dev, prod }, null, 2)};\n`;

fs.writeFileSync(new URL('./config.js', import.meta.url), banner + body);

function summarize(label, block) {
  if (block) {
    console.log(`  ${label}: configured (scene "${block.scene.sceneName}" @ ${block.networkHost})`);
  } else {
    console.log(
      `  ${label}: NOT configured — set C3D_APPLICATION_API_KEY_${label.toUpperCase()} and ` +
        `C3D_SCENE_ID_${label.toUpperCase()} in examples/validation-app/.env`
    );
  }
}

console.log('C3D validation-app config written to examples/validation-app/config.js');
summarize('dev', dev);
summarize('prod', prod);
